### ISSUE TITLE
关于训练集和测试集精度问题

### ISSUE THREAD

**Issue by Blueskymax** [xyanchen/WiFi-CSI-Sensing-Benchmark#4]
我用了提供的数据集和代码，但是为什么我每次训练，训练一个epoch后验证集和训练集的精度就能都达到100%，对此很困惑。数据集用的NTU-Fi_HAR，试了ResNet18、LSTM、BiLSTM都是这样。
![screenshot 2023-02-20 175211](https://user-images.githubusercontent.com/73003060/220073002-b9551aa6-5b0b-4fbb-aa12-0ff44ab800ae.png)

**Comment by Henry-Avery** [comment]
我也问过这个问题，以为是数据读入或者算Accuracy的时候有问题，等我再看下能不能找到原因

**Comment by Blueskymax** [comment]
> 我也问过这个问题，以为是数据读入或者算Accuracy的时候有问题，等我再看下能不能找到原因

是的，感谢评论，就是读取数据出错了，作者用的linux系统，文件读取用的/，应该换成\\就对了

**Comment by Marsrocky** [comment]
Yes windows和linux的文件目录加载不同导致的，我们在README里写了要用linux，如果windows需要改。
