### ISSUE TITLE
请问具体怎么改啊，我用Pycharm运行这个代码也遇到了这个问题> 我也问过这个问题，以为是数据读入或者算Accuracy的时候有问题，等我再看下能不能找到原因

### ISSUE THREAD

**Issue by wcl928461363** [xyanchen/WiFi-CSI-Sensing-Benchmark#6]
> 我也问过这个问题，以为是数据读入或者算Accuracy的时候有问题，等我再看下能不能找到原因

是的，感谢评论，就是读取数据出错了，作者用的linux系统，文件读取用的/，应该换成\\就对了

_Originally posted by @Blueskymax in https://github.com/xyanchen/WiFi-CSI-Sensing-Benchmark/issues/4#issuecomment-1447470791_

**Comment by Blueskymax** [comment]
![image](https://user-images.githubusercontent.com/73003060/224635238-511f7928-a67c-436f-ba06-291e64df6cdc.png)
在data.py文件中，改成这样

**Comment by Marsrocky** [comment]
Data加载问题，我们默认是linux的/，如果用windows的数据目录都是\，斜杠换掉就可以了。
